Return host if it is healthy or degraded for both read and write policy,
Nextdoor/envoy pull request #150
Opened 2021-09-20 20:49 UTC by ronakts

TODO: test on local.

Commit Message:
Additional Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]
[Optional [API Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

2021-09-20 21:12 UTC, stlava requested changes

2021-09-20 21:12 UTC, stlava commented on source/extensions/clusters/redis/redis_cluster_lb.cc
> +Upstream::HostConstSharedPtr returnPrimaryIfHealthy(Upstream::HostConstSharedPtr primary_host) {
Please add a config to toggle this functionality.

2021-09-20 21:12 UTC, stlava commented on source/extensions/clusters/redis/redis_cluster_lb.cc
>      hosts = host_set.degradedHosts();
Add toggle to only return healthy host (same toggle as below to require primary be healthy).

2021-09-22 18:43 UTC, ronakts commented
created new PR https://github.com/Nextdoor/envoy/pull/154

2021-09-22 18:43 UTC, closed without merging